### ISSUE TITLE
Diretório de components

### ISSUE THREAD

**Issue by nathpaiva** [fesanto/ecommerce#4]
## história de usuário

Como desenvolvedores queremos ter um novo diretório chamado `components`, esse diretório será usado para fazer a criação de todos os coponentes que usaremos na aplicação.

## critério de aceitação

- [x] o diretório `components` deve estár no `root`
- [x] esse diretório deve ter um `index.ts` (o `index.ts` será responsável por exportar todos os componentes para a aplicação.

## definição de feito

- [x] Ao acessar o projeto demove ter disponível esse novo diretório criar.

**Comment by fesanto** [comment]
"Ao acessar o projeto demove ter disponível esse novo diretório criar."
Não entendi. 

Dentro desse intex.ts eu crio um componente?

**Comment by nathpaiva** [comment]
Escrevi errado 😂  é `index.ts`.

Então, nesse arquivo só vamos exportar os components, tipo esse arquivo: [Material UI](https://github.com/mui-org/material-ui/blob/master/packages/mui-base/src/index.js)
